spring:
  datasource:
    url: jdbc:h2:file:./addon-db;DB_CLOSE_DELAY=-1
    username: sa
    password:

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}